### ISSUE TITLE
notify users of messages

### ISSUE THREAD

**Issue by bjmckenz** [oceancypress/student_information_system#327]
Home page for users hasa "Unread messages" block if there are unread messages (no block - no messages)

Testing:
* find a user with unread messages: 
As of sat night:
Apollo Titania  normal=1 priority=0
Ares Titania  normal=1 priority=0
Daryl Bailey  normal=1 priority=0
Dionysus Titania  normal=1 priority=0
Deanna Rogers  normal=1 priority=1
Ellia Hill  normal=1 priority=0
Hades Titania  normal=2 priority=0
Hera Titania  normal=2 priority=0
Jordan Johnson  normal=1 priority=0
Jordan Richardson  normal=0 priority=1
Julian Warren  normal=1 priority=0
Jasmine Wilson  normal=1 priority=0
Lucy Mitchell  normal=1 priority=0
Lenny Riley  normal=1 priority=1
Lily Roberts  normal=0 priority=1
Lilianna Tucker  normal=1 priority=0
Max Alexander  normal=1 priority=0
Myra Myers  normal=1 priority=0
Naomi Williams  normal=1 priority=0
Penelope Foster  normal=1 priority=1
Sydney Owens  normal=1 priority=0
Valeria Morgan  normal=1 priority=0
Victor Payne  normal=1 priority=0
Zeus Titania  normal=1 priority=0
* log in.
* See count.
*

**Comment by oceancypress** [comment]
numbers are very off from what you have here, not sure if this is a bug or if the values have just changed @bjmckenz

**Comment by oceancypress** [comment]
when I hit filter on the sent messages table it gives me a NoReverseMatch error @bjmckenz

**Comment by bjmckenz** [comment]
yep, fixed that.

**Comment by bjmckenz** [comment]
numbers: they changed.
