### ISSUE TITLE
test data for students ignores capacity

### ISSUE THREAD

**Issue by bjmckenz** [oceancypress/student_information_system#332]
Fixed. 
Testing:
* (kinda hard to test)
* go to Sections. Sort by remaining.
* verify no entries have <-
* (that's how I spotted in the first place, seriously)
*

**Comment by liannadevries09** [comment]
This worked so I am going to pass it but the sort took about 30 second and my laptop sounded like it was going to blow up. Here is the screenshot of the waiting message. Let me know if you want me to open a bug ticket for long sort time. 
![image](https://user-images.githubusercontent.com/71474266/114494145-d4836c00-9be9-11eb-847e-1fb0a499a84e.png)

**Comment by oceancypress** [comment]
Keeping this open and moving to todo to discuss @liannadevries09 comment with @bjmckenz

**Comment by oceancypress** [comment]
jk closing because sorting taking a long time has nothing to do with this bug
