### ISSUE TITLE
fix test_admin_excluded

### ISSUE THREAD

**Issue by bjmckenz** [oceancypress/student_information_system#337]
test did not catch real problem. Hacked User is a temp fix. Disabled the test.

**Comment by liannadevries09** [comment]
@bjmckenz - does this one need testing?

**Comment by bjmckenz** [comment]
Sure:
Testhing:
* look at Users list
* Verify "Admin" is not present.
*

**Comment by liannadevries09** [comment]
Admin is still available. Testing is documented in this ticket: https://github.com/csufmse/student_information_system/issues/328

**Comment by bjmckenz** [comment]
er, I think this is the good admin. I'm not seeing bad admin (account "admin")

To be sure, do this:
Testing:
* go to /siteadmin (Django admin site)
* create a user "foobar" , mark staff, superuser
* log into /schooladmin with one of our admin accounts (hades)
* verify foobar is not in list of Users.
*

**Comment by liannadevries09** [comment]
Added adminli as a staff and super user. Then logged in as hades and I can see adminli in the User list still.
![image](https://user-images.githubusercontent.com/71474266/115647353-9ffe6700-a2f1-11eb-9b24-fb12d9387d14.png)

**Comment by bjmckenz** [comment]
Oh. My. Gosh. You would not believe this. OK, it was broken ONLY THE FIRST TIME. Thereafter the admin user was properly hidden. It was because the first time, we query but don't write to the DB -- and that query has the effect of writing to the DB. And my exclusion required the writing to the DB. So it worked "subsequently" but not the first time.

You could prove this to yourself (before applying this fix) by doing the same steps, seeing adminli, going to another page (say Students) and coming back. adminli will be gone.

So now there is a special exclusion for "first timers".

Testing:
* create adminli
* log in as hades
* see adminli is gone
* go to another page, come back to users, see it is STILL gone.

Thank you very much for sticking with this!
