### ISSUE TITLE
transcript tweaks

### ISSUE THREAD

**Issue by bjmckenz** [oceancypress/student_information_system#344]
It's great -- really clean!

Could we get:
* per semester GPA
* per course row, Major name?
** would not remove the major abbreviation from the course, just add a leading column with the major name.
* overall GPA
* date prepared/as of
*

**Comment by jeffreicher** [comment]
noted in bl

**Comment by bjmckenz** [comment]
Testing: 
* observe formatting
* amaze at per-semester gpa, credits earned
* swoon at class level header, space between semesters, and cumulative credits earned
* yawn at date-prepared.
