### ISSUE TITLE
course catalog numbers are sorted lexicographically, not numerically

### ISSUE THREAD

**Issue by bjmckenz** [oceancypress/student_information_system#353]
1 < 2 < 20 < 3 < 30 < ...
as opposed to 
1 < 2 < 3 <20 < 30

**Comment by jeffreicher** [comment]
noted in bl

**Comment by bjmckenz** [comment]
Testing: create a course with number "2". See that it sorts before -100, etc.

**Comment by liannadevries09** [comment]
approving. sub tickets are complete.
