### ISSUE TITLE
School info should be accessible without login

### ISSUE THREAD

**Issue by bjmckenz** [oceancypress/student_information_system#359]
Majors, Professors, Courses, Sections.

NO students, messages, demographics.

(this is in support of bringing Professor and Student up to par, #324 and #281)

**Comment by bjmckenz** [comment]
Testing:
* log out.
* go to /sis/majors, /sis/courses, /sis/semesters, /sis/professors. See pages.

**Comment by liannadevries09** [comment]
/sis/majors works but the rest of them dont.
![image](https://user-images.githubusercontent.com/71474266/115648520-8eb65a00-a2f3-11eb-831f-1fd5027620e8.png)

**Comment by bjmckenz** [comment]
Yeah, I broke this with the back-button stuff. Did not have a solution at the time; was thinking of descoping. Fortunately I thought of a solution!

**Comment by oceancypress** [comment]
there is a button called new user on the professor tab, is this intended? other than that lgtm

**Comment by bjmckenz** [comment]
nope, that's a bug. will fx.
