### ISSUE TITLE
Dates issue needs to be resolved so that students can register for classes

### ISSUE THREAD

**Issue by jeffreicher** [oceancypress/student_information_system#361]
Completes SID-05

**Comment by bjmckenz** [comment]
Added headers to page that show current semester and any semesters open for registration
TEsting:
* log in as each (A,P,S)
* observe header, verify links work
* verify correct from list of semesters
* for bonus testing, set up "no" current semester, verify "Currnet" disappears
* same for Reg, verify works with 0, 1, more.
*

**Comment by bjmckenz** [comment]
**NOTE THAT LINKS WILL NOT WORK FOR Professor and Student UNTIL "281-263-etc" PR is merged**. And even then, it might need to be tweaked.
