### ISSUE TITLE
New User button visible on Professor for non-admin users

### ISSUE THREAD

**Issue by bjmckenz** [oceancypress/student_information_system#448]

**Comment by bjmckenz** [comment]
Testing:
* log in as professor. Click Professors. See no "New User" button.
* log in as student...
* after logout, go to /schooladmin/professors...

**Comment by liannadevries09** [comment]
New User button is still available
![image](https://user-images.githubusercontent.com/71474266/116010420-cfacb800-a5ec-11eb-9bf6-d986bfcc159e.png)
